# Just an example how to check and upgrade the sonoff-tasmota from the Home Assistant
script:   
  check_sonoffs_version:
      sequence:
        - service: mqtt.publish
          data_template:
            topic: "cmnd/sonoffs/status"
            payload: 2

sensor:  
  - platform: command_line
    name: Sonoff latest release
    command: "curl -s https://github.com/arendst/Sonoff-Tasmota/releases/latest | grep -o 'v[0-9]*.[0-9]*.[0-9]*'"
    scan_interval: 43200 #12H
  - platform: mqtt
    name: Sonoff POW Boiler Version
    state_topic: "stat/sonoff1/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff POW HomeCCTV Version
    state_topic: "stat/sonoff2/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff Touch Kitchen Version
    state_topic: "stat/sonoff3/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff HallWay Light Version
    state_topic: "stat/sonoff4/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff XiaomiCCTV Version
    state_topic: "stat/sonoff5/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff iFan Bedroom Version
    state_topic: "stat/sonoff_ifan/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
