homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HomeLatitude
  longitude: !secret HomeLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include config/customize.yaml
  packages: !include_dir_named config/packages
  whitelist_external_dirs:
    - /config # - /home/homeassistant/.homeassistant/
    - /config/tmp # - /home/homeassistant/.homeassistant/tmp
    - /config/backup/hass #- /home/homeassistant/backup/hass

system_health:


# Enables the frontend

frontend:
  javascript_version: latest #auto
  themes: !include_dir_merge_named themes
  # extra_html_url:
lovelace:
  mode: yaml

recorder: !include config/recorder.yaml
#The history component will track everything that is going on within HA.
#It depends on the recorder component for storing the data and uses the same DB.
history:

#The logbook component provides a different perspective on the history of your 
#house by showing all the changes that happened to your house in reverse chronological order.
#It depends on the recorder component for storing the data.
logbook:

# api:
zeroconf:

http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret api_password
  # ssl_certificate: !secret ssl_certificatePATH
  # ssl_key: !secret ssl_keyPATH 
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  #NGINX-Restricting it to only listen to 127.0.0.1 will forbid direct accesses.
  #Also, Home Assistant should be told to trust headers coming from the NGINX proxy only. 
  #Otherwise, incoming requests will always come from 127.0.0.1 and not the real IP address.
  #So make sure to add the NGINX server ip in trusted_proxies
  trusted_proxies:
    - XXX.XXX.XXX.XXX #CHANGE TO IP - localhost
    - XXX.XXX.XXX.XXX #CHANGE TO IP - nginx
    ### add the api ngix reslover??
  cors_allowed_origins:
    - https://cast.home-assistant.io    

# #ASUSWRT ORIGNAL (merlin)
asuswrt:
  host: 192.168.1.1
  username: !secret AsusWrtUsername
  password: !secret AsusWrtPassword
  protocol: telnet
  port: 23  


device_tracker: !include config/device_trackers.yaml

#Xiaomi Gateway (Aqara) #YAML configuration of the Xiaomi Aqara integration has been deprecated since 0.112
# xiaomi_aqara:
#   discovery_retry: 6
#   gateways:
#     - host: 192.168.XXX.XXX #CHANGE_IP
#       mac: !secret XiaomiGatewayMAC
#       key: !secret XiaomiGatewayKey
 
vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum
    host: 192.168.XXX.XXX #CHANGE_IP
    token: !secret XiaomiVacuumV1Token
    
#Google Cast devices like Android TVs and Chromecasts will be automatically 
#discovered if you enable the discovery component.
#https://www.home-assistant.io/components/cast/    
# cast:
#   media_player:
#   - host: 192.168.1.104 #partnerTV
  
# apple_tv:
#   - host: 192.168.1.121
#     name: Apple TV
#     login_id: !secret AppleTVLogin_id
#     # credentials: !secret AppleTVcredentials

timer:
  #a Timer that Start Every time that the Home Door Open 
  dogwalk:
    duration: '00:30:00'
    icon: mdi:dog-side

mqtt:
  password: !secret mqtt_password
  #To use the Embedded MQTT Broker - Remove the 3 line below
  # I am using Eclipse Mosquitto broker for my setup.
  broker: !secret MainHostIP
  client_id: HOME_ASSISTANT
  username: homeassistant
  
# Enables configuration UI
config:

#for HA Update Available Notification
updater:

discovery:
  # ignore:
  #   - igd

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret DarkSky_API_KEY
    mode: daily

# Text to speech
tts:
  - platform: google_translate #english 

#update every 1 hour. -using dns-o-matic for better updates via Router UI
cloudflare:
  email: !secret MyEmail 
  api_key: !secret CloudflareAPIKey
  zone: !secret CloudflareZone
  records:
    - !secret CloudflareSubDomain1

# https://www.home-assistant.io/components/cloud/ - 
# not in use-made alexa and google_assistant integration manualy. 
# cloud:
    
# https://www.home-assistant.io/components/notify.telegram/
telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret TelegramChatIDNum1 
# https://custom-components.github.io/hacs/
hacs:
  token: !secret github_access_token
  
# https://github.com/ualex73/monitor_docker
monitor_docker:
  - name: Docker
    containers:
      - unifi-controller
      - letsencrypt
      - code-server #vscode
      - mosquitto #mqtt
      - openvpn-as #VPN
    scan_interval: 20
    rename:
      unifi-controller: UniFi
      letsencrypt: Let's Encrypt
      code-server: VS-Code
      mosquitto: MQTT Mosquitto
      openvpn-as: Open VPN
    monitored_conditions:
      - state #for each docker container
      - status #for each docker container
      - uptime #for each docker container
      - image #for each docker container
      - cpu_percentage #for each docker container
      - memory_percentage #for each docker container
      - allinone #make one sensor for each docker container insted of 1 for state,status,version etc...
      - containers_running
      - containers_memory_percentage
      - containers_cpu_percentage
      # - containers_total
climate:
  - platform: sensibo
    api_key: !secret SensiboApiKey
#https://www.home-assistant.io/components/logger/
logger:
  default: warning # Possible log severity levels, listed in order from most severe to least severe, are: 
                                              #critical #fatal #error #warning #warn #info #debug #notset
  logs:
    homeassistant.components.http.ban: warning
    # custom_components.monitor_docker: debug

jewish_calendar:

google:
  client_id: !secret Google_CLIENT_ID
  client_secret: !secret Google_CLIENT_SECRET
# calendar:
#   - platform: todoist
#     token: !secret todoist_token

#YAML configuration of the TUYA integration has been deprecated since 0.112
# tuya:
#   username: !secret tuya_username
#   password: !secret tuya_password
#   country_code: 972

airvisual:
    api_key: airvisual_api_key
    geographies:
        latitude: !secret HomeLatitude
        longitude: !secret HomeLongitude

####################################### Speedtest.Net #######################################     
speedtestdotnet:
  server_id: 9034 #018 Server  
# zoneminder:
#   host: 192.168.1.200:8081  

##############
## includes - at external folder
############
sensor: !include config/sensors.yaml
group: !include config/groups.yaml 
automation: !include_dir_merge_list config/automation/
script: !include config/scripts.yaml
input_select: !include config/input_select.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
binary_sensor: !include config/binary_sensors.yaml  
camera: !include config/cameras.yaml
#stream: #to enable sream from camera in google home (make bugs for shell scripts)
switch: !include config/switchs.yaml  
fan: !include config/fans.yaml  
remote: !include config/remotes.yaml  
light: !include config/lights.yaml  
yeelight: !include config/yeelight.yaml 
mobile_app:
ios: !include config/ios.yaml
notify: !include config/notify.yaml
panel_iframe: !include config/panel_iframe.yaml
zone: !include config/zones.yaml
shell_command: !include config/shell_commands.yaml
homekit: !include config/homekit.yaml # For apple HomeKit support
#alexa support Via Haaska (v3) #to avoid from monthly payments (in Home Assitant Cloud) #and to give more options for customization
# alexa: !include config/alexa.yaml #NOT IN USE
google_assistant: !include config/google_assistant.yaml 
rest_command: !include config/rest_commands.yaml 
############################################################################
##
## sonoff1 = sonoff POW R2 boiler ( switch.mqtt_pow1 )
## ####### sonoff2 = sonoff POW R2 2 -Now For HEATER (switch.mqtt_pow2) - NOT IN USE
## sonoff3 = sonoff TX T2EU1C - BedRoom Light ( light.bedroom )
## sonoff4 = sonoff basic -now for Hallway Light (light.sonoff_hallway_light )
## ####### sonoff5 = sonoff basic - now for salon CCTV ( switch.sonoff_salon ) - NOT IN USE
## sonoff6 = sonoff TX 2CH - 1 Kitchen 2 special (now sonoff8)
## sonoff7 = sonoff touch NO LIVE WIRE (T4EU1C) - bathroom light light.bathroom
## sonoff_ifan = sonoff ifan02 with light and fan speed contoll at bedroom
## sonoff8 = sonoff touch NO LIVE WIRE (T4EU1C) - service light
## sonoff9 = sonoff basic - now for Kitchen CCTV ( switch.sonoff_kitchen )
## ####### sonoff99 = sonoff touch - SPARE 1CH
##
############################################################################

############################# ENTITY NAMES CHANGES ############################# 
## binary_sensor.motion_sensor_158d0000e62376 = binary_sensor.xiaomi_motion_sensor_hallway
## sensor.illumination_34ce0088d2f7 = sensor.xiaomi_gateway_illumination
## binary_sensor.door_window_sensor_158d0000d834ac = binary_sensor.door_sensor_bedroom
## binary_sensor.door_window_sensor_158d0001b714e9 = binary_sensor.door_sensor_main_entrance
## sensor.humidity_158d0001150e4e = sensor.humidity_bedroom_0 --> sensor.humidity_bathroom
## sensor.temperature_158d0001150e4e = sensor.temperature_bedroom_0 --> sensor.temperature_bathroom
## light.gateway_light_34ce0088d2f7 = light.gateway_light
## switch.10515080cc50e337683d = switch.fan
## binary_sensor.motion_sensor_158d0004455e9f = binary_sensor.motion_sensor_bathroom
################################################################################
