################################################################################
#
#CAMERA
#
################################################################################
# Vstarcam Home 01
# - platform: onvif
#   name: Home CCTV1
#   host: !secret HomeCCTV1IP
#   port: 10080
#   username: !secret HomeCCTV1username
#   password: !secret HomeCCTV1password
  # extra_arguments: 'extra_arguments: -rtsp_transport udp
  
#Vstarcam Home 01
# - platform: ffmpeg
#   name: Home CCTV1
#   input: !secret HomeCCTV1URL

- platform: ffmpeg
  name:  IPC01 Kitchen
  input: !secret kitchen_ipc01_URL

#Vstarcam Home 02  
# - platform: onvif
#   name: Home CCTV2
#   host: !secret HomeCCTV1IP
#   port: 10080
#   username: !secret HomeCCTV2username
#   password: !secret HomeCCTV2password 


#hikvision Home CCTV2
# #IMOU ranger 
# - platform: ffmpeg 
#   name: ipc02_salon
#   input: !secret IPC02_Salon_URL
  
- platform: ffmpeg 
  name: Outdoor CCTV
  input: !secret IPC03_OUTDOORURL
# - platform: onvif
#   name: Outdoor CCTV
#   host: !secret IPC03_OUTDOOR_IP
#   profile: 1 # 0 for SuperHD
#   port: 80
#   username: !secret IPC03_OUTDOOR_username
#   password: !secret IPC03_OUTDOOR_password 
  
    

- platform: local_file #for security warnings 
  file_path: '/config/tmp/home_cctv1.png'
  name: "ipc01_snapshot"
  
#Vstarcarm Outdoor Eliran 
# - platform: onvif
#   name: Outdoor CCTV
#   host: !secret OutdoorCCTVIP
#   port: 10080
#   username: !secret OutdoorCCTVusername
#   password: !secret OutdoorCCTVpassword

#HIKVISION Outdoor CCTV 4MP
# - platform: ffmpeg
#   name: Outdoor CCTV
#   input: !secret OutdoorCCTV_02_URL  

# - platform: mjpeg
#   name: Home_01
#   mjpeg_url: !secret blueiris_home01_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
# - platform: mjpeg
#   name: Home_02
#   mjpeg_url: !secret blueiris_home02_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
# - platform: mjpeg
#   name: IPC10
#   mjpeg_url: !secret blueiris_ipc10_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
