################################################################################
#
#CAMERA
#
################################################################################
# Vstarcam Home 01
# - platform: onvif
#   name: Home CCTV1
#   host: !secret HomeCCTV1IP
#   port: 10080
#   username: !secret HomeCCTV1username
#   password: !secret HomeCCTV1password
  # extra_arguments: 'extra_arguments: -rtsp_transport udp
  
#Vstarcam Home 01
- platform: ffmpeg
  name: Home CCTV1
  input: !secret HomeCCTV1URL

#Vstarcam Home 02  
# - platform: onvif
#   name: Home CCTV2
#   host: !secret HomeCCTV1IP
#   port: 10080
#   username: !secret HomeCCTV2username
#   password: !secret HomeCCTV2password 
#hikvision Home CCTV2

- platform: ffmpeg 
  name: Home CCTV2
  input: !secret HomeCCTV2URL
  
- platform: onvif
  name: Outdoor CCTV
  host: !secret IPC10_IP
  profile: 1 # 0 for SuperHD
  port: 80
  username: !secret IPC10username
  password: !secret IPC10password
    

- platform: local_file #for security warnings 
  file_path: '/config/tmp/home_cctv1.png'
  name: "CCTV1_Snapshot"
  
#Vstarcarm Outdoor Eliran 
# - platform: onvif
#   name: Outdoor CCTV
#   host: !secret OutdoorCCTVIP
#   port: 10080
#   username: !secret OutdoorCCTVusername
#   password: !secret OutdoorCCTVpassword

#HIKVISION Outdoor CCTV 4MP
# - platform: ffmpeg
#   name: Outdoor CCTV
#   input: !secret OutdoorCCTV_02_URL  

# - platform: mjpeg
#   name: Home_01
#   mjpeg_url: !secret blueiris_home01_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
# - platform: mjpeg
#   name: Home_02
#   mjpeg_url: !secret blueiris_home02_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
# - platform: mjpeg
#   name: IPC10
#   mjpeg_url: !secret blueiris_ipc10_URL 
#   username: !secret blueiris_admin_username
#   password: !secret blueiris_admin_password
#   authentication: basic
