      name: My Floorplan
      image: /local/custom_ui/floorplan/floorplan.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css
      # These options are optional
      # warnings:                  # enable warnings (to find out why things might ot be working correctly)
      # pan_zoom:                  # enable experimental panning / zooming
      # hide_app_toolbar:          # hide the application toolbar (when used as a custom panel)
      date_format: DD-MMM-YYYY   # Date format to use in hover-over text
      
      last_motion_entity: binary_sensor.xiaomi_motion_sensor_hallway
      last_motion_class: last-motion
#########################GROUPS#########################
      groups:
        - name: Time
          entities:
            - sensor.date_time
            - sensor.time
#########################Lights#########################
        - name: Lights     
          entities:
            - light.sonoff_hallway_light
            - light.kitchen
            - light.philips_bulb
            - group.salon_light
            - light.desk_lamp
          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
            - state: 'unavailable'
              class: 'unavailable-status'
            - state: 'unknown'
              class: 'unknown-status'
              
          action:
            domain: homeassistant
            service: toggle
#########################Doors#########################
        - name: Doors
          entities:
            - binary_sensor.door_sensor_main_entrance #home door
            - binary_sensor.door_sensor_bedroom #bedroom door
          states:
            - state: 'off'
              class: 'door_closed90'
            - state: 'on'
              class: 'door_open90' 
#########################Sensors Status#########################
        - name: Sensors Status
          entities:
             - sensor.temperature_bedroom_0
             - sensor.humidity_bedroom_0
             - switch.mqtt_pow1 #boiler
             - binary_sensor.xiaomi_motion_sensor_hallway
          states:
            - state: 'on'
              class: 'color_green'
            - state: 'off'
              class: 'color_red'
            - state: 'unavailable'
              class: 'unavailable-status'
#########################Device Tracker#########################
        - name: Device_Tracker
          entities:
            - device_tracker.eliran_iphone_wifi #byIP at DDWT 
            - device_tracker.shiran_iphone_wifi #shiran
          states:
            - state: 'home'
              class: 'tracker_home'
            - state: 'not_home'
              class: 'tracker_not_home' 
#########################Cameras#########################
        - name: Cameras
          entities:
            - camera.outdoor_cctv
            - camera.home_cctv1
            - camera.home_cctv2
          states:
            - state: 'idle'
              class: 'camera-idle'

        - name: Camera Images
          entities:
            - entity: camera.outdoor_cctv
              element: camera.outdoor_cctv.image
          camera_image_template: '${entity.attributes.entity_picture}'
#########################Switchs#########################
        - name: Switchs     
          entities:
            - switch.mqtt_pow2 #cctv1
            - switch.sonoff_xiaomicctv_switch #cctv2

          states:
            - state: 'on'
              class: 'switch-on'
            - state: 'off'
              class: 'switch-off'
            - state: 'unavailable'
              class: 'unavailable-status'
            - state: 'unknown'
              class: 'unknown-status'
              
          action:
            domain: homeassistant
            service: toggle
            
            
            
            
            
            
            
#########################Switchs#########################
        # - name: Status     
        #   entities:
        #     - switch.mqtt_pow1 #boiler
        #     - binary_sensor.xiaomi_motion_sensor_hallway
        #   states:
        #     - state: 'on'
        #       class: 'light-on'
        #     - state: 'off'
        #       class: 'light-off'
#        - name: thermostat_temp
#          entities:
#            - climate.downstairs
#            - climate.upstairs
#          text_template: '${entity.attributes.current_temperature ? entity.attributes.current_temperature : "undefined"}'
#
# The above text_template uses extended attributes from the climate.* objects to get current temperature.

#        - name: text_states
#          entities:
#            - sensor.downstairs_thermostat_humidity
#            - sensor.dark_sky_temperature
#            - sensor.last_message
#          text_template: '${entity.state ? entity.state.replace(/\s{2,}/g,"") : "undefined"}'
#
# The above text_template uses jQuery syntax to search and replace any instance of 2 consecutive (or more) spaces in a string of text.
