##################################################
#
# GOOGLE ASSISTANT - The Manual Way without monthly Payment.
# https://www.home-assistant.io/components/google_assistant/#first-time-setup
#
##################################################
  
  project_id: !secret Google_Home_project_id
  # secure_devices_pin: !secret Google_Home_secure_devices_pin
  service_account: 
    private_key: !secret private_key_GoogleAssistantAPI
    client_email: !secret client_email_GoogleAssistantAPI
  report_state: true  
  # api_key: !secret Google_Home_API_KEY_or
  
  exposed_domains:
    - light
    - switch
    - vacuum
    # - script
    # - media_player
    #- climate #using Sensibo Skill
    
  entity_config:
    sensor.sensibo1_temp:
      name: Salon Temperature
      room: Salon
      aliases:
        - Home Temperature
        - Salon Temperature
        - Home Temp
########################################
###LIGHTS
########################################
    light.white_bulb:
      name: Left Bulb
      room: Salon

    light.living_room_color_bulb:
      name: Right Bulb
      room: Salon

    light.kitchen:
      name: Kitchen
      room: Kitchen
      aliases:
        - Kitchen light

    light.service_room:
      name: Service
      room: Service
      aliases:
        - Service light
        - Philips light
    light.sonoff_hallway_light:
      name: Misdaron
      room: Hallway
      aliases:
        - Hallway
        - MISSDARON
        - MISSDARON light
    light.bathroom:
      name: bathroom
      room: bathroom
      aliases:
        - bathroom
        - bathroom light        
    light.gateway_light:
      name: Gateway
      room: Kitchen
      aliases:
        - GateWay light
        
    light.desk_lamp:
      name: Desk Lamp
      room: Hallway
      aliases:
        - Desk Lamp
        - Desktop Lamp
        
    light.bedroom:
      name: Bedroom light
      room: Bedroom
      aliases:
        - Bedroom light
###############expose: FALSE##################
    light.special_sonoff_kitchen:
      expose: false
########################################
###SWITCHS
########################################
    switch.sonoff_kitchen:
      name: Kitchen Camera switch
      room: Kitchen
      aliases:
        - Kitchen Camera 
      
    switch.mqtt_pow2:
      name: Radiator
      room: Bedroom
            
    # switch.sonoff_salon:
    #   name: Salon Camera switch
    #   room: Salon
    #   aliases:
    #     - Salon Camera 
      
    switch.tv_lg:
      name: TV
      room: Salon
      
    switch.tv_lg_vol:
      name: Volume
      room: Salon
      aliases:
        - Volume TV
        - TV Volume
    switch.tv_lg_mute:
      name: Mute
      room: Salon
      aliases:
        - Mute TV
        - TV Mute
        
    switch.mqtt_pow1:
      name: Boiler
      room: Hallway
      
    switch.xiaomi_powerstrip:
      name: Power strip
      room: Salon

    switch.fan:
      name: Fan
      room: Salon
      aliases:
        - Red Fan
        - Floor Fan
###############expose: FALSE##################
    switch.tv_lg_hdmi1:
      expose: false
    switch.tv_lg_hdmi2:
      expose: false
    switch.tv_lg_hdmi3:
      expose: false
    switch.docker_code_server:
      expose: false
    switch.docker_letsencrypt:
      expose: false
    switch.docker_mosquitto:
      expose: false
    switch.docker_openvpn_as:
      expose: false
    switch.docker_unifi_controller:
      expose: false
    switch.sensibo_living_room:
      expose: false    
    # switch.ha_dockermon_organizr:
    #   expose: false

########################################
###CAMERAS
########################################
    camera.ipc01_kitchen:
      name: Kitchen Camera
      room: Kitchen
    # camera.ipc02_salon:
    #   name: Salon Camera
    #   room: Salon
    camera.outdoor_cctv:
      name: Outdoor Camera
      room: Garage
      aliases:
        - Outside camera
########################################
###INPUT BOOLEAN
########################################      
    input_boolean.alarm_clock_status:
      expose: false
    input_boolean.boiler_off_clock_status:
      expose: false
    input_boolean.boiler_on_clock_status:
      expose: false
    input_boolean.weather:
      expose: false
########################################
###Vaccum
########################################      
    vacuum.xiaomi_vacuum:
      name: Vaccum Cleaner
      room: Hallway
      aliases:
        - Roobik
########################################
###SCRIPTS
########################################
    script.restart_home_assistant:
      name: Restart Home Assitant
      room: Garage
    script.reboot_router:
      name: Reboot Router
      room: Garage
    script.backup_ha_and_move_backup_to_unraid:
      name: Backup Home Assitant
      room: Garage
    script.reboot_ap:
      name: Reboot AP
      room: Garage      
###############expose: FALSE##################
    script.backup_ha_config:
      expose: false    
    script.check_sonoffs_tasmota_status:
      expose: false    
    script.update_hass:
      expose: false
    script.timer_off_boiler:
      expose: false
    script.backup_all_os:
      expose: false
    script.test_push:
      expose: false
    script.white_night_light:
      expose: false
    script.purple_night_light:
      expose: false
    script.flash_gateway1:
      expose: false
    script.flash_gateway2:
      expose: false
    script.install_after_update_hass:
      expose: false
    script.update_speedtestnet:
      expose: false 
    script.close_rdp_port:      
      expose: false     
########################################
###GROUP
########################################  
    group.all_my_climate:
      expose: false
    group.all_my_lights:
      expose: false
    group.all_my_switchs:
      expose: false
    group.bathroom_lights:
      expose: false
    group.bedroom_lights:
      expose: false
    group.kitchen_lights:
      expose: false
    group.office_lights:
      expose: false
    group.salon_lights:
      expose: false
########################################
###GENERAL
########################################      
    binary_sensor.xiaomi_motion_sensor_hallway:
      name: Hallway motion
      expose: true
########################################
###CLIMATE- not in use - Sensibo Skill better!
########################################      
#     climate.living_room:
#       name: AC
#       room: Salon
#       aliases:
#         - MAZGAN
#         - Air con
#         - Air conditioning
#         - Air conditioner
########################################
###MEDIA PLAYER
########################################      
    # media_player.apple_tv:
    #   name: Apple TV
    #   room: Salon
    
    #  
    # media_player.partnertv #discover by Google Home APP
    #