################################################################################
#
#GROUPS
#
################################################################################
salon_lights:
  name: תאורה בסלון
  entities:
    - light.white_bulb
    - light.living_room_color_bulb
    - light.all_salon_lights

office_lights:
  name: תאורה במסדרון
  entities:
    - light.sonoff_hallway_light
    - light.desk_lamp
    - light.all_hallway_lights

kitchen_lights:
  name: תאורה במטבח
  entities:
    - light.kitchen
    - light.service_room
    - light.gateway_light
    - light.all_kitchen_lights

bedroom_lights:
  name: תאורה בחדר שינה
  entities:
    - light.bedroom

bathroom_lights:
  name: תאורה במקלחת
  entities:
    - light.bathroom

all_my_lights:
  name: כל התאורה בבית
  entities:
    - light.white_bulb
    - light.living_room_color_bulb
    - light.kitchen
    - light.service_room
    - light.sonoff_hallway_light
    - light.desk_lamp
    - light.bedroom
    - light.bathroom
    - light.gateway_light

all_my_climate:
  name: מזגנים
  entities:
    - climate.living_room
    - climate.bedroom

all_my_switchs:
  name: All Switchs
  icon: mdi:power-socket-eu
  entities:
    - switch.fan
    - vacuum.xiaomi_vacuum
    - switch.sonoff_kitchen
    - switch.mqtt_pow1
    - climate.living_room
    - climate.bedroom
    - switch.tv_lg
    - switch.tv_lg_vol
    - switch.tv_lg_hdmi1
    - switch.tv_lg_hdmi2
    - switch.tv_lg_hdmi3
    - switch.mqtt_pow2
