################################################################################
#
#HOMEKIT (Apple Smart Home)
#
################################################################################
  filter:
    include_entities:
      - climate.living_room
      - vacuum.xiaomi_vacuum
      - binary_sensor.xiaomi_motion_sensor_hallway
      - sensor.humidity_bedroom_0
      - sensor.xiaomi_gateway_illumination
      - sensor.temperature_bedroom_0
      # - device_tracker.homeipad
      - device_tracker.eliran_iphone_wifi #byIP at DDWT 
      - device_tracker.shiran_iphone_wifi #shiran
      - device_tracker.xiaomigateway
      - device_tracker.sonoff_kitchen #Kitchen lamp sonoff TX
      - device_tracker.sonoff_bedroom #sonoff touch 
      - device_tracker.sonoff_kitchen_cctv_switch #sonoff pow2 kitchen cctv switch
      - device_tracker.homecctv_01 #HomeCCTV VStarcam 360 
      - device_tracker.hikvision_home_cctv
      - device_tracker.rockrobo #Xiaomi Vaccum Cleaner Gen1
      - device_tracker.main_server #main server 
      - device_tracker.windows_vm #Windows VM
      - device_tracker.ipc_10
      - sensor.sensibo1_temp
      - sensor.sensibo1_humidity
      # not in use - using sensibo
      # - script.ac_turn_off
      # - script.ac_turn_on
      # - script.ac_fan_speed
      # - input_boolean.ac_status_alexa
      - script.restart_home_assistant
      - script.reboot_router
      - script.backup_ha_and_move_backup_to_unraid
    include_domains:
      - light
      - switch
      - binary_sensor
      
    exclude_entities:
      - light.yeelight_white_f0b4290e4e68 #Duplicate
      - light.yeelight_rgb_286c07106e1b #Duplicate
      - switch.tv_lg_hdmi1
      - switch.tv_lg_hdmi2
      - switch.tv_lg_hdmi3
      - switch.tv_lg_vol
      - binary_sensor.floorplan
      - binary_sensor.switch_158d0000d8c836
      - binary_sensor.switch_158d000149b9ab
      - binary_sensor.wall_switch_both_158d0001712d0e
      - binary_sensor.wall_switch_left_158d0001712d0e
      - binary_sensor.wall_switch_right_158d0001712d0e
      - binary_sensor.wall_switch_both_158d0001e119a7
      - binary_sensor.wall_switch_left_158d0001e119a7
      - binary_sensor.wall_switch_right_158d0001e119a7
      - binary_sensor.ha_dockermon_cloud9ide
      - binary_sensor.ha_dockermon_ha_dockermon
      - binary_sensor.ha_dockermon_heimdall
      - binary_sensor.ha_dockermon_letsencrypt
      - binary_sensor.ha_dockermon_unifi
      - binary_sensor.ha_dockermon_unms
  entity_config:
########################################
###LIGHT
########################################  
    #all light. get "display_categories: LIGHT"  by default
    light.kitchen:
      name: מטבח
    light.desk_lamp:
      name: מנורת שולחן
    light.gateway_light:
      name: רכזת
    light.living_room_color_bulb:
      name: סלון ימנית
    light.white_bulb:
      name: סלון שמאלית
    light.philips_bulb:
      name: חדר שירות
    light.sonoff_hallway_light:
      name: מסדרון
    light.bathroom:
      name: מקלחת
    light.bedroom:
      name: חדר שינה
########################################
###SWITCH
########################################  
    #all switch. get "display_categories: SWITCH"  by default
    switch.mqtt_pow2:
      name: מצלמת מטבח
    switch.sonoff_xiaomicctv_switch:
      name: מצלמת סלון
    switch.mqtt_pow1:
      name: דוד
      type: shower
    switch.xiaomi_powerstrip:
      name: מפצל שקעים
    switch.tv_lg:
      name: טלויזיה
########################################
###SCRIPT
########################################  
    script.restart_home_assistant:
      name: איתחול הום אסיסטנט
    script.ac_fan_speed:
      name: מהירות מזגן
    script.reboot_router:
      name: Reboot Router
    script.reboot_AP:
      name: Reboot AP      
########################################
###DEVICE TRACKER 
########################################
    # device_tracker.homeipad:
    #   name: אייפד
    device_tracker.eliran_iphone_wifi:
      name: אלירן
    device_tracker.shiran_iphone_wifi:
      name: שירן
    device_tracker.xiaomigateway:
      name: רכזת
    device_tracker.sonoff_kitchen:
      name: מנורת מטבח
    device_tracker.sonoff_bedroom:
      name: תאורת חדר שינה  
    device_tracker.sonoff_kitchen_cctv_switch:
      name: מפסק מצלמת מטבח
    device_tracker.homecctv_01:
      name: מצלמת מטבח
    device_tracker.salon_cctv_switch:
      name: מפסק מצלמת סלון
    device_tracker.hikvision_home_cctv:
      name: מצלמת סלון
    device_tracker.sonoffpow1:
      name: מצב דוד
    device_tracker.main_server:
      name: שרת ראשי
    device_tracker.windows_vm:
      name: וינדוס וירטואל
    device_tracker.ipc_10:
      name: 10 מצלמת חוץ
########################################
###BINARY SENSOR
########################################
    binary_sensor.bi_hom01_motion:
      name: תנועה מצלמת בית סלון
    binary_sensor.bi_hom02_motion:
      name: תנועה מצלמת בית כניסה
    binary_sensor.bi_ipc10_motion:
      name: תנועה מצלמת חוץ 10
    binary_sensor.door_sensor_bedroom:
      name: דלת חדר הורים
    binary_sensor.door_sensor_main_entrance:
      name: דלת ראשית  
    binary_sensor.xiaomi_motion_sensor_hallway:
      name: תנועה במסדרון 
########################################
###SENSOR
########################################         
    sensor.xiaomi_gateway_illumination:
      name: עוצמת אור ברכזת
    sensor.temperature_bedroom_0:
      name: טמפרטורה בחדר הורים
    sensor.humidity_bedroom_0:
      name: לחות בחדר הורים
    sensor.sensibo1_temp:
      name: טמפרטורה בסלון     
    sensor.sensibo1_humidity:
      name: לחות בסלון
########################################
###GENERAL
########################################  
    vacuum.xiaomi_vacuum:
      name: רוביק
    group.allmylights:
      name: כל התאורה
    climate.living_room:      
      name: מזגן בסלון
 
