################################################################################
#  IOS
## this is my Actionable notifications options 
## more info at: https://www.home-assistant.io/docs/ecosystem/ios/notifications/actions/
## more code in the end of automations.ymal
################################################################################

  push:
    categories:
      - name: homelights
        identifier: 'modifymylights' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'ALLMYLIGHTS_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את כל האורות בבית'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
          - identifier: 'ONLY_KITCHEN_LIGHT_ON' #(MUST BE UPPER CASE)
            title: 'השאר במטבח בלבד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'ONLY_SALON_R_LIGHT_ON' #(MUST BE UPPER CASE)
            title: 'השאר סלון ימין בלבד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'            
          - identifier: 'ONLY_GATEWAY_LIGHT_ON' #(MUST BE UPPER CASE)
            title: 'השאר תאורה חלשה בלבד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            
      - name: cctv
        identifier: 'modifymycctvswitch' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'ALLMYCCTV_INHOME_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את כל המצלמות בתוך הבית'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
          - identifier: 'CCTV_KITCHEN_ON' #(MUST BE UPPER CASE)
            title: ' הדלק את מצלמת מטבח'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'CCTV_XIAOMI_ON' #(MUST BE UPPER CASE)
            title: 'הדלק את מצלמת סלון'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'ALLMYCCTV_INHOME_ON' #(MUST BE UPPER CASE)
            title: 'הדלק את כל המצלמות בתוך הבית'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

      - name: modifyboiler
        identifier: 'modifymyboilerswitch' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'BOILER_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את הדוד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
          - identifier: 'BOILER_ON' #(MUST BE UPPER CASE)
            title: ' הדלק את הדוד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'BOILER_ON_BY_TIMER' #(MUST BE UPPER CASE)
            title: 'הדלק לזמן שנקבע באפליקציה'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'

      - name: modifyheater
        identifier: 'modifymyheaterswitch' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'HEATER_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את הדוד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
          - identifier: 'HEATER_ON' #(MUST BE UPPER CASE)
            title: ' הדלק את הדוד'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'HEATER_ON_BY_TIMER' #(MUST BE UPPER CASE)
            title: 'הדלק לזמן שנקבע באפליקציה'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'

      - name: feeddogopt
        identifier: 'feedthedog' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'DOG_FEEDED' #(MUST BE UPPER CASE)
            title: 'זורו אכל כבר'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
            
      - name: aircon
        identifier: 'modifyaircon' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'LIVINGROOM_AIRCON_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את המזגן בסלון'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'
          - identifier: 'BEDROOM_AIRCON_OFF' #(MUST BE UPPER CASE)
            title: 'כבה את המזגן בחדר השינה'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'

            
      - name: vaccum
        identifier: 'vaccum_cleaner' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'START_VACCUM_CLEANER' #(MUST BE UPPER CASE)
            title: 'הפעל את השואב'
            activationMode: 'background'
            authenticationRequired: no
            destructive:  no #yes for red color
            behavior: 'default'
          - identifier: 'STOP_VACCUM_CLEANER' #(MUST BE UPPER CASE)
            title: 'עצור את השואב'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'RETURN_TO_BASE_VACCUM_CLEANER' #(MUST BE UPPER CASE)
            title: 'החזר לעגינה'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

      - name: rdp
        identifier: 'close_rdp_port' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'CLOSE_RDP_PORT' #(MUST BE UPPER CASE)
            title: 'סגור את הפורט הפתוח'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'

      - name: vpn
        identifier: 'close_vpn_docker' #(MUST BE LOWER CASE)
        actions:
          - identifier: 'CLOSE_VPN_DOCKER' #(MUST BE UPPER CASE)
            title: 'סגור את הקונטיינר'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #yes for red color
            behavior: 'default'