################################################################################
#
#LIGHT
#
################################################################################
    #Xiaomi Philips LED Blub
  - platform: xiaomi_miio
    name: Philips Bulb 
    host: XXX.XXX.XXX.XXX #CHANGE_IP
    token: !secret PhilipsBulbToken
    model: philips.light.bulb
    #Xiaomi YeeLight Blubs and Desk lamp
  - platform: yeelight  #CHANGE_IP
    devices:
      XXX.XXX.XXX.XXX: #At home
        name: Living Room Color Bulb
      XXX.XXX.XXX.XXX:
        name: White Bulb
      XXX.XXX.XXX.XXX:
        name: Desk Lamp
      #light.gateway_light- is Working by default via Discovery 

################################################################################
## sonoff3 = sonoff touch - Kitchen Light ( light.sonoff_light )
################################################################################
  - platform: mqtt
    name: "Sonoff Light"
    state_topic: "stat/sonoff3/POWER"
    command_topic: "cmnd/sonoff3/POWER"
    availability_topic: "tele/sonoff3/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
################################################################################
## sonoff4 = sonoff basic - Hallway Light (light.sonoff_hallway_light )
################################################################################
  - platform: mqtt
    name: "Sonoff HallWay Light"
    state_topic: "stat/sonoff4/POWER"
    command_topic: "cmnd/sonoff4/POWER"
    availability_topic: "tele/sonoff4/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
################################################################################
## sonoff_ifan = sonoff ifan02 -in the bedroom
################################################################################    
  - platform: mqtt
    name: "Bedroom fan light"
    command_topic: "cmnd/sonoff_ifan/power"
    state_topic: "stat/sonoff_ifan/POWER1"
    availability_topic: "tele/sonoff_ifan/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
    payload_available: "Online"
    payload_not_available: "Offline"
    
################################################################################
## hyperion APA102 LED STRIP
################################################################################    
  # - platform: hyperion
  #   host: XXX.XXX.XXX.XXX #CHANGE_IP
  # - platform: rpi_gpio_pwm #????
  #   leds:
  #     - name: LightStrip
  #       driver: pca9685
  #       pins: [3, 4, 5, 6] # [R, G, B, W]
  #       type: rgbw
  
  
  
# ################################################################################
# ## sonoff01= sonoff T1 3CH 
# ################################################################################
#   - platform: mqtt
#     name: "Living room 01"
#     state_topic: "stat/sonoff01/POWER1"
    # value_template: '{{ value_json.POWER }}' #added new
#     command_topic: "cmnd/sonoff01/POWER1"
#     availability_topic: "tele/sonoff01/LWT"
#     qos: 1
#     payload_on: "ON"
#     payload_off: "OFF"
#     payload_available: "Online"
#     payload_not_available: "Offline"
#     retain: false
    
#   - platform: mqtt
#     name: "Living room 02"
#     state_topic: "stat/sonoff01/POWER2"
#     value_template: '{{ value_json.POWER }}' #added new
#     command_topic: "cmnd/sonoff01/POWER2"
#     availability_topic: "tele/sonoff01/LWT"
#     qos: 1
#     payload_on: "ON"
#     payload_off: "OFF"
#     payload_available: "Online"
#     payload_not_available: "Offline"
#     retain: false
#   - platform: mqtt
#     name: "Living room 03"
#     state_topic: "stat/sonoff01/POWER3"
#     value_template: '{{ value_json.POWER }}' #added new
#     command_topic: "cmnd/sonoff01/POWER3"
#     availability_topic: "tele/sonoff01/LWT"
#     qos: 1
#     payload_on: "ON"
#     payload_off: "OFF"
#     payload_available: "Online"
#     payload_not_available: "Offline"
#     retain: false
