################################################################################
#
#NOTIFY
#
#################################################################################
  # Get notify in the main TV
  # https://www.home-assistant.io/components/notify.nfandroidtv/
  - platform: nfandroidtv
    name: partner_tv
    host: 192.168.1.104

  - name: eliran_telegram
    platform: telegram
    chat_id: !secret TelegramChatIDNum1

  - name: shiran_and_eliran_ios #to send the same notify together 
    platform: group
    services:
      - service: ios_elirantur2
    #   - service: ios_shiran_iphone
      
  - name: eliran_ios_and_ipad_and_telegram #to send the same notify together 
    platform: group
    services:
      - service: eliran_telegram
      - service: ios_elirantur2
      - service: ios_homeipad
      