################################################################################
#
#RECORDER
#
################################################################################
#To make the DataBase mare clean and "Slim", Remove some entities etc..
purge_keep_days: 7
exclude:
  domains:
    - weblink
    - updater
    - group
    - input_number
    - input_select
    - zone
  entities:
    - sun.sun
    - script.tv_vol_down
    - script.tv_input
    - script.tv_vol_down
    - script.tv_vol_up
    - sensor.alarm_clock_hour
    - sensor.alarm_clock_minute
    - sensor.alarm_clock_time_long
    - switch.tv_lg
    - switch.tv_lg_hdmi1
    - switch.tv_lg_hdmi2
    - switch.tv_lg_hdmi3
    - switch.tv_lg_vol
    - binary_sensor.home_door_battery_low
    - binary_sensor.motion_battery_low
    - binary_sensor.bedroom_door_battery_low
    - binary_sensor.switch_v1_battery_low
    - binary_sensor.switch_v2_battery_low
    - binary_sensor.wall_switch_battery_low
    - group.alarm_clock
    - group.alerts
    - input_number.slider_boiler
    - script.test_push
    - automation.ac_off_for_alexa
    - automation.ac_on_for_alexa
    - automation.battery_notification
    - automation.battery_notification_clear
    - automation.battery_sensor_from_battery_attribute
    - automation.battery_sensor_from_battery_level_attribute
    - automation.battery_sensor_from_battery_numeric_attribute
    - automation.clean_aquarium_reminder
    - automation.control_devices
    - automation.daily_hass_backup
    - automation.dog_walk_started
    - automation.drinkingwater_filter_reminder
    - automation.enable_automation_630_am
    - automation.feed_the_dog_evening
    - automation.feed_the_dog_morning
    - automation.hikvision_cctv_is_on_alert
    - automation.home_cctv_is_on_alert
    - automation.hot_temperature_alert
    - sensor.custom_card_tracker
    - sensor.custom_component_tracker
    - sensor.hline_1
    - sensor.hline_2
    - sensor.hline_3
    - sensor.hline_4
    - sensor.hline_5
    - sensor.hline_6
    - sensor.time
    - sensor.date_time
    - binary_sensor.wall_switch_both_158d0001e119a7
    - binary_sensor.wall_switch_left_158d0001e119a7
    - binary_sensor.wall_switch_right_158d0001e119a7
    - input_number.boiler_off_clock_hour
    - input_number.boiler_off_clock_minute
    - input_number.boiler_on_clock_hour
    - input_number.boiler_on_clock_minute
    - input_number.slider_boiler
    - group.docker_container
    - sensor.home_assistant_docker_latest_image_build
    - sensor.dark_sky_humidity_1
    - sensor.dark_sky_humidity_2
    - sensor.dark_sky_humidity_3
    - sensor.dark_sky_humidity_4
    - sensor.dark_sky_humidity_5
    - sensor.dark_sky_daytime_high_temperature_1
    - sensor.dark_sky_daytime_high_temperature_2
    - sensor.dark_sky_daytime_high_temperature_3
    - sensor.dark_sky_daytime_high_temperature_4
    - sensor.dark_sky_daytime_high_temperature_5
    - sensor.dark_sky_daily_max_precip_intensity_1
    - sensor.dark_sky_daily_max_precip_intensity_2
    - sensor.dark_sky_daily_max_precip_intensity_3
    - sensor.dark_sky_daily_max_precip_intensity_4
    - sensor.dark_sky_daily_max_precip_intensity_5
    - sensor.dark_sky_icon_1
    - sensor.dark_sky_icon_2
    - sensor.dark_sky_icon_3
    - sensor.dark_sky_icon_4
    - sensor.dark_sky_icon_5
    - sensor.dark_sky_overnight_low_temperature_1
    - sensor.dark_sky_overnight_low_temperature_2
    - sensor.dark_sky_overnight_low_temperature_3
    - sensor.dark_sky_overnight_low_temperature_4
    - sensor.dark_sky_overnight_low_temperature_5
    - sensor.dark_sky_precip_intensity_1
    - sensor.dark_sky_precip_intensity_2
    - sensor.dark_sky_precip_intensity_3
    - sensor.dark_sky_precip_intensity_4
    - sensor.dark_sky_precip_intensity_5
    - sensor.dark_sky_precip_probability_1
    - sensor.dark_sky_precip_probability_2
    - sensor.dark_sky_precip_probability_3
    - sensor.dark_sky_precip_probability_4
    - sensor.dark_sky_precip_probability_5
    - sensor.dark_sky_pressure_1
    - sensor.dark_sky_pressure_2
    - sensor.dark_sky_pressure_3
    - sensor.dark_sky_pressure_4
    - sensor.dark_sky_pressure_5
    - sensor.dark_sky_summary_1
    - sensor.dark_sky_summary_2
    - sensor.dark_sky_summary_3
    - sensor.dark_sky_summary_4
    - sensor.dark_sky_summary_5
    - sensor.dark_sky_visibility_1
    - sensor.dark_sky_visibility_2
    - sensor.dark_sky_visibility_3
    - sensor.dark_sky_visibility_4
    - sensor.dark_sky_visibility_5
    - sensor.dark_sky_wind_bearing_1
    - sensor.dark_sky_wind_bearing_2
    - sensor.dark_sky_wind_bearing_3
    - sensor.dark_sky_wind_bearing_4
    - sensor.dark_sky_wind_bearing_5
    - sensor.dark_sky_wind_speed_1
    - sensor.dark_sky_wind_speed_2
    - sensor.dark_sky_wind_speed_3
    - sensor.dark_sky_wind_speed_4
    - sensor.dark_sky_wind_speed_5
    - binary_sensor.floorplan
    - sensor.time_of_day
    - sensor.time_online_ha
    - sensor.hass_uptime
    - sensor.unraid_uptime
    - sensor.last_boot