################################################################################
#
#ZONE
#
#################################################################################
  # This will override the default home zone
  - name: Home
    latitude: !secret HomeLatitude
    longitude: !secret HomeLongitude
    radius: 20
    icon: mdi:home-heart
    
  - name: SCE
    latitude: !secret CollegeLatitude
    longitude: !secret CollegeLongitude
    radius: 300
    icon: mdi:school

  - name: Work
    latitude: !secret WorkLatitude
    longitude: !secret WorkLongitude
    radius: 7000
    
  - name: Zalman
    latitude: !secret SvetHomeLatitude
    longitude: !secret SvetHomeLongitude
    radius: 20
    icon: mdi:home
    
  - name: Turgeman
    latitude: !secret TurHomeLatitude
    longitude: !secret TurHomeLongitude
    radius: 25
    icon: mdi:home-outline
    
  - name: SuperPharm
    latitude: !secret SuperPharmLatitude
    longitude: !secret SuperPharmLongitude
    radius: 35
    icon: mdi:pharmacy

  - name: SapirCollege
    latitude: !secret SapirLatitude
    longitude: !secret SapirLongitude
    radius: 500
    icon: mdi:school
